services:
  web:
    container_name: community-exchange-web
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    environment:
      DB_HOST: db
      DB_NAME: community_exchange_dev
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/community-exchange
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: community-exchange-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: community_exchange_dev
    ports:
      - "5432:5432"
volumes:
  postgres_data: {}
networks:
  default:
    name: community_exchange_default
